apiVersion: v2
name: trivy-operator-collector
description: Collects trivy-operator scan reports from a cluster into an S3 bucket

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time
# you make changes to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "v0.6.0"
