apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}-api
  labels:
    {{- include "server.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
